### ISSUE TITLE
Twitter login falis: "Desktop applications only support the oauth_callback value 'oob'"

### ISSUE THREAD

**Issue by inator** [appback/hoodie-plugin-social#26]
Error: Desktop applications only support the oauth_callback value 'oob'
   at Strategy.parseErrorResponse (/home/social-example/app/node_modules/hoodie-plugin-social/node_modules/passport-twitter/lib/strategy.js:182:10)
   at Strategy.OAuthStrategy._createOAuthError (/home/social-example/app/node_modules/hoodie-plugin-social/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16)
   at /home/social-example/app/node_modules/hoodie-plugin-social/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41
   at /home/social-example/app/node_modules/hoodie-plugin-social/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
   at passBackControl (/home/social-example/app/node_modules/hoodie-plugin-social/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/social-example/app/node_modules/hoodie-plugin-social/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.EventEmitter.emit (events.js:117:20)
   at _stream_readable.js:919:16
   at process._tickDomainCallback (node.js:463:13)

**Comment by inator** [comment]
As we just discovered, this is a the result of an appropriate Callback URL in the Twitter API settings.  https://app_host:port/_api/_auth/twitter/callback is required.  Error handling for the above case needs to be added.

**Comment by inator** [comment]
@joaoneto:  Can you provide a pull request to add the necessary error checking?

**Comment by joaoneto** [comment]
@inator, ok, i'll fix this

**Comment by joaoneto** [comment]
@inator
done the callback setup in twitter apps...
email is not present, but still get the following error:
Failed to find token request in session
     at Strategy.OAuthStrategy.authenticate
